sudo: required
services:
  - docker

before_install:
  - docker build -t docker-reactor -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker-reactor npm run test -- --coverage

after_success:
  - docker build -t rajshahdev/multi-client Dockerfile ./client
  - docker build -t rajshahdev/multi-nginx Dockerfile ./nginx
  - docker build -t rajshahdev/multi-server Dockerfile ./server
  - docker build -t rajshahdev/multi-worker Dockerfile ./worker
  # Login to dockerhub
  # - docker login -u "$DOCKER_USER" -p "$DOCKER_PWD"
  - echo "\$DOCKER_PWD" | docker login -u "\$DOCKER_USER" --password-stdin
  - docker push rajshahdev/multi-client
  - docker push rajshahdev/multi-nginx 
  - docker push rajshahdev/multi-server
  - docker push rajshahdev/multi-worker 
