sudo: required
services:
  - docker

before_install:
  - docker build -t docker-reactor -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker-reactor npm run test -- --coverage

after_success:
  - docker build -t rajshahdev/multi-client Dockerfile ./client
  - docker build -t rajshahdev/multi-nginx Dockerfile ./nginx
  - docker build -t rajshahdev/multi-server Dockerfile ./server
  - docker build -t rajshahdev/multi-worker Dockerfile ./worker
