sudo: required
services:
  - docker

before_install:
  - docker build -t docker-reactor -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker-reactor npm run test -- --coverage

after_success:
  - docker build -t rajshahdev/multi-client -f ./client/Dockerfile ./client
  - docker build -t rajshahdev/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t rajshahdev/multi-server -f ./server/Dockerfile ./server
  - docker build -t rajshahdev/multi-worker -f ./worker/Dockerfile ./worker
  # Login to dockerhub
  # - docker login -u "$DOCKER_USER" -p "$DOCKER_PWD"
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push rajshahdev/multi-client
  - docker push rajshahdev/multi-nginx 
  - docker push rajshahdev/multi-server
  - docker push rajshahdev/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-245505614209'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY